### ISSUE TITLE
unexpectedly high valences depicted by depict-ligands.py

### ISSUE THREAD

**Issue by nbehrnd** [OpenChemistry/fragments#13]
The submission of SMILES strings in a .smi to this script in a virtual environment of Python 3.11.6 and RDKit 2023.09.2 (PyPI, packaged by November 25th; there is no more recent *packaged* version by RDKit on https://github.com/rdkit/rdkit/releases) modifies the structures: bond orders greater than one seem to be lost, some of the valences are unexpected.

In an attempt to prepare the IMes ligand of the Grubbs catalyst, Avogadro's SMILES string

```
Cc1cc(C)cc(c1N1CCN(C1*)c1c(C)cc(cc1C)C)C	IMes
```

yields

![IMes](https://github.com/OpenChemistry/fragments/assets/19709084/a7d22b64-5899-4952-890c-47c909164665)

while openbabel depicts this as

![obabel_IMes](https://github.com/OpenChemistry/fragments/assets/19709084/f4008011-3c2c-4b24-ad9c-ea22123981df)

Because simple pyridine

```
c1cccnc1	pyridine
```

is depicted as 

![pyridine](https://github.com/OpenChemistry/fragments/assets/19709084/5e7e777b-c66d-404c-9a51-f5d87f675d3e)

the cause of the problem need not be in Avogadro.

[2023-12-05_IMes_problem.zip](https://github.com/OpenChemistry/fragments/files/13559516/2023-12-05_IMes_problem.zip)

**Comment by ghutchis** [comment]
Closed by #14
